wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1670253593.741481
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.15
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 512
episodes:
  desc: null
  value: 250
label:
  desc: null
  value: train
learning_rate:
  desc: null
  value: 3e-4
reward:
  desc: null
  value: ''
start_datetime:
  desc: null
  value: 2022-12-05_08:19:48
